// <auto-generated />
namespace BibliotecaOnline.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Image_Upload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Image_Upload));
        
        string IMigrationMetadata.Id
        {
            get { return "201811122218016_Image_Upload"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
